### PR TITLE
Makes code compatible with Python3 (still supports python2)

### PR DESCRIPTION
**Pull request by evandromr**
This PR makes a few changes to make the code compatible with Python3, while still supporting python2.

### CODE REVIEW

**Comment by nocturnalastro** [comment]
Thanks I didn't know anyone else was using the code. 

Would you mind using `from six.moves import input`. It removes the need for testing the python version.
 
I also think that something along the lines of :
```
flags = ["  -w                the working dir (default will be `./`) WorkDir must exist & be writable",
         #"  -i <file>         a script to run before running xstar",
         "  -k                keep log: do not delete after successful run",
         "  -l <log>          redirect console output to log file",
         "  -n <N>           set max number processes per host to N (default: 4)",
         #"  -j  <file|param>  a joblist or a xstinitable parameters",
         "  -h,--help         prints this message",
         "  -s,--no-help     surpresses help message so you can run with defaults"]

print("""
multixstar: manages parallel execution of multiple XSTAR jobs, with python's multiprocessing module
Version {version}

Usage:  multixstar [options] <joblist|params>

Supported options are:

{flags}

Normally xstinitable will be launched to prompt for XSTAR physical
parameters and generate a list of XSTAR jobs to run in parallel.
This can be customized by supplying xstinitable parameters on the
command line (such as mode=h) OR by supplying the name of an 
existing joblist file, in which case xstinitable will not be run
nor will the generated spectra be collated into a single table
model with xstar2table.
""".format(version=__version__, flags ="\n".join(flags)))
```

would offer a bit more flexible as is would allow the easy addition of flags in the future. I do plan on implementing/testing the other flags at some point.
oh also we need a `__version___=0.1.1` or something

If you don't want do this (you've already done a lot thanks), I can open up a new after merging this.
Cheers,
Micky

**Comment by evandromr** [comment]
Hi Micky,

Yes, I can make those changes.

 But one think to keep in mind is that importing `input` from `six` will make `six` a dependence. This should probably be said somewhere in the README file.

Related to the flags, I was just experimenting in using Python's [`argparse`](https://docs.python.org/3.6/library/argparse.html#module-argparse) instead of [`getopt`](https://docs.python.org/3.6/library/getopt.html), would you be interested in implementing that? That would be another PR.

Thanks for the feedback :+1:

**Comment by nocturnalastro** [comment]
Thanks and I think six is relatively common, I'm pretty sure it would be fine as a dependence but I agree it should be mentioned in the read me.

**Comment by evandromr** [comment]
Ready for review

**Pull request merged**
